version: "3"

services:
  tools:
    image: registry.cn-hangzhou.aliyuncs.com/zgang/tools:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./storage:/app/storage
    container_name: tools

  redis:
    image: redis:3.2.12
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    container_name: redis3.2
    command: redis-server --requirepass zhoupassword112a21

  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswordexam
    container_name: mysql5.7