appName: ZhouTools
appEnv: prod # [local, dev, prod]
appPort: 8905

log:
  level: info #[fatal, error, warn, info, debug]
  logdir: storage

# mysql 5.7
database:
  host: 127.0.0.1
  user: root
  dbname: test
  pwd: root

redis:
  host: 127.0.0.1
  pwd: yourpassword